trigger:
  branches:
    include:
      - main

pool:
  name: "Self-hosted-pool"

variables:
  - group: terraform-secrets-dev
  - name: TF_ENVIRONMENT
    value: "dev"
  - name: TF_VAR_FILE
    value: "env/dev/dev.tfvars"
  - name: TF_BACKEND_KEY
    value: "dev.terraform.tfstate"

stages:
  - stage: DeployDev
    displayName: "Terraform Apply (Dev)"
    jobs:
      - job: TerraformDev
        displayName: "Terraform Init, Plan & Apply (Dev)"
        steps:
          - checkout: self

          - pwsh: |
              terraform -version
              az --version
            displayName: "Check Tools"

          - pwsh: |
              Write-Host "Terraform Init for Dev"
              terraform init `
                -backend-config="resource_group_name=rg-digwi-terraform-remote" `
                -backend-config="storage_account_name=stgdigwiterraformstate" `
                -backend-config="container_name=tfstate" `
                -backend-config="key=$(TF_BACKEND_KEY)"

              terraform validate

              Write-Host "Terraform Plan for Dev"
              terraform plan -input=false -var-file="$(TF_VAR_FILE)" -out=tfplan

              Write-Host "Terraform Apply for Dev"
              terraform apply -auto-approve tfplan
            displayName: "Terraform Init, Plan & Apply"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)