trigger: none 
pr: none 

pool:
  name: "Self-hosted-pool"

parameters:
  - name: environment
    displayName: "Select Environment to Destroy"
    type: string
    default: "dev"
    values:
      - dev
      - prod

  - name: confirm_destroy
    displayName: "Type YES to confirm destroy"
    type: string
    default: "NO"

variables:
  - group: terraform-secrets-dev

 
  - name: TF_BACKEND_RESOURCE_GROUP
    value: "rg-digwi-terraform-remote"
  - name: TF_BACKEND_STORAGE_ACCOUNT
    value: "stgdigwiterraformstate"
  - name: TF_BACKEND_CONTAINER_NAME
    value: "tfstate"

stages:
  - stage: Destroy
    displayName: "Terraform Destroy (${{ parameters.environment }})"
    jobs:
      - deployment: TerraformDestroy
        displayName: "Terraform Destroy Job"
        environment: "${{ parameters.environment }}" 
        pool:
          name: "Self-hosted-pool"

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - pwsh: |
                    if ("${{ parameters.confirm_destroy }}" -ne "YES") {
                      Write-Error "Destroy aborted — confirmation required. Please type YES to confirm."
                      exit 1
                    }

                    Write-Host "Proceeding to destroy ${{ parameters.environment }} environment..."

                    $env:TF_ENVIRONMENT = "${{ parameters.environment }}"
                    $env:TF_BACKEND_KEY = "$env:TF_ENVIRONMENT.terraform.tfstate"
                    $env:TF_VAR_FILE = "env/$env:TF_ENVIRONMENT/$env:TF_ENVIRONMENT.tfvars"

                    Write-Host "Terraform Init for $env:TF_ENVIRONMENT"
                    terraform init `
                      -backend-config="resource_group_name=$(TF_BACKEND_RESOURCE_GROUP)" `
                      -backend-config="storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT)" `
                      -backend-config="container_name=$(TF_BACKEND_CONTAINER_NAME)" `
                      -backend-config="key=$env:TF_BACKEND_KEY"

                    Write-Host "Planning destroy..."
                    terraform plan -destroy -var-file="$env:TF_VAR_FILE" -out=tfplan

                    Write-Host "Applying destroy plan..."
                    terraform apply -auto-approve tfplan
                  displayName: "Terraform Plan & Destroy"
                  env:
                    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
                    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
                    ARM_TENANT_ID: $(ARM_TENANT_ID)
                    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
